controllers:
    resource:
        path: ../src/ex04Bundle/Controller/
        namespace: App\ex04Bundle\Controller
    type: attribute

ex04_index:
    path: /ex04
    controller: App\ex04Bundle\Controller\ex04Controller::indexAction
    methods: [GET, POST]

ex04_index_slash:
    path: /ex04/
    controller: App\ex04Bundle\Controller\ex04Controller::indexAction
    methods: [GET, POST]

ex04_delete:
    path: /ex04/delete/{id}
    controller: App\ex04Bundle\Controller\ex04Controller::deleteAction
    methods: [GET]