controllers:
    resource:
        path: ../src/ex02Bundle/Controller/
        namespace: App\ex02Bundle\Controller
    type: attribute

ex02_controller_index:
    path: /ex02
    controller: App\ex02Bundle\Controller\ex02Controller::indexAction
    methods: [GET, POST]