controllers:
    resource:
        path: ../src/ex03Bundle/Controller/
        namespace: App\ex03Bundle\Controller
    type: attribute

ex03_index:
    path: /ex03
    controller: App\ex03Bundle\Controller\DefaultController::indexAction
    methods: [GET, POST]