controllers:
    resource:
        path: ../src/ex14Bundle/Controller/
        namespace: App\ex14Bundle\Controller
    type: attribute

employee_index:
    path: /ex13
    controller: App\ex13Bundle\Controller\EmployeeController::index
    methods: [GET]

employee_index_slash:
    path: /ex13/
    controller: App\ex13Bundle\Controller\EmployeeController::index
    methods: [GET]

employee_save:
    path: /employee/save/{id}
    controller: App\ex13Bundle\Controller\EmployeeController::save
    defaults: { id: null }
    methods: [GET, POST]

employee_delete:
    path: /employee/delete/{id}
    controller: App\ex13Bundle\Controller\EmployeeController::delete
    methods: [POST, GET]