controllers:
    resource:
        path: ../src/ex01Bundle/Controller/
        namespace: App\ex01Bundle\Controller
    type: attribute

ex01_routes:
    resource: ../src/ex01Bundle/Controller/
    type: attribute
    prefix: /e01